### ISSUE TITLE
[BUG] Fix being able to push code with linting issues

### ISSUE THREAD

**Issue by TimJentzsch** [TimJentzsch/valveGamesAnnouncerBot#71]
**Describe the bug**
I have been able to push code with a linting issue:
![Linting issue](https://cdn.discordapp.com/attachments/475368486634258447/589009191163789316/unknown.png)
The issue gets recognized by VSCode and Travis CI cought the issue.

**Expected behavior**
The push should fail while any linting issues are present.

**Comment by zachkont** [comment]
Merging https://github.com/TimJentzsch/valveGamesAnnouncerBot/pull/74 will fix a Windows path issue with the lint script. However, keep in mind the following scenario:

* make a change that violates a lint rule
* `git add` that change
* `git commit` will now fail because lint fails
* fix the error
* do **not** `git add `the fix
* `git commit` now completes successfully because lint passes

This will of course be caught by the CI so it's not a real issue but ideally I would like to run lint only on staged files as a pre-commit hook. There is a package called [lint-staged](https://github.com/okonet/lint-staged) which looks promising but until then the above will be an issue.

**Comment by TimJentzsch** [comment]
There seems to be an inconcistency with TSLint and Prettier with the following code snippet:
```js
$('#PatchSelector option').each(function () {
  const option = $(this).val();
  // botLogger.info(option);
  if (option !== 'Select an Update...') {
    patchList.push(option);
  }
});
```
The linter wants it to be `function ()`, giving an error otherwise, but Prettier formats it to `function()`.
